name: reseda
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7.0
    - matplotlib
    - numpy
    - pandas
    - seaborn
    - jupyter
    - notebook
    - ipykernel
    - scikit-learn
    - scikit-bio
    - scipy
    - pyyaml
    - xlsxwriter
    - biopython
    - gzip
    - regex
#    - igraph   # needs to be changed: install by downloading the package and manual install
    - textdistance
    - bokeh
    - holoviews

